### DISCUSSION TITLE
Installation issue of v1.11.0

### DISCUSSION THREAD

**Discussion by choonho** [cloudforet-io/community#121] [Q&A] [answered]
# Installation Issue of Version 1.11.0

If you have any problems of installation. Please add comments.

**Comment by yangmingyu2020** [comment]
Hello, I encountered an issue while following the installation guide at https://cloudforet.io/ko/docs/setup_operation/installation/on_premise/

After performing the step [5. Initialize the configuration], when I run the command
$ kubectl logs initializer-5f5b7b5cdc-abcd1 -n spaceone

I see the following error log, and I'm unable to proceed with the subsequent steps
```
TASK [Create Marketplace Repository] ***********************************************************************************
(ERROR) =>
Server is unavailable. (channel = repository.portal.spaceone.dev:50051, message = Channel is not ready.)
>> Spec: {"resource_type": "repository.Repository", "data": {"domain_id": "domain-64aba901a19b", "name": "Marketplace", "repository_type": "remote", "endpoint": "grpc://repository.portal.spaceone.dev:50051"}, "mode": "EXEC", "verb": {"read": "list", "create": "create", "update": "update", "exec": "register"}, "matches": [], "no_verification": true}
```
I suspect that there might be an incorrect configuration in the initializer.yaml file, specifically in the marketplace_endpoint section. 

Could you please provide guidance on how to resolve this issue?

**Comment by GeunjeLEE** [comment]
Hi @yangmingyu2020 :)

When you run the initializer, Cloudforet try to connect to open-source marketplace.
But, There are cases where the marketplace's grpc channel is unavailable due to network issues in the on-premise environment.

So, you can install cloudforet with local mode instead of default mode.

please reinstall initializer with local mode.
https://github.com/cloudforet-io/spaceone-initializer#local-mode-without-marketplace
(Also, We will update document to install with default mode)

If you get an other error, Please continue to leave comments.

---

1. uninstall initializer
```bash
helm install initializer -n spaceone
```

2. modify initializer values.yaml with local mode
```yaml
main:
  import:
    - /root/spacectl/apply/root_domain.yaml
    - /root/spacectl/apply/create_managed_repository.yaml
    - /root/spacectl/apply/user_domain.yaml
    - /root/spacectl/apply/create_role.yaml
    - /root/spacectl/apply/add_statistics_schedule.yaml
    - /root/spacectl/apply/print_api_key.yaml
  var:
    domain:
      root: root
      user: spaceone
    default_language: ko
    default_timezone: Asia/Seoul
    domain_owner:
      id: admin
      password: Admin123!@#         # Change your password
    user:
      id: system_api_key
```

3. reinstall initializer
```bash
helm install initializer cloudforet/spaceone-initializer -n spaceone -f initializer.yaml
```
