### DISCUSSION TITLE
[NHN Cloud] Enable skeleton plugin

### DISCUSSION THREAD

**Discussion by choonho** [cloudforet-io/community#144] [Mentorship]
# Install Cloudforet

https://cloudforet.io/docs/setup_operation/quick_install/

# Use CLI tool

> For spacectl CLI tools
> Following commands should be executed in spacectl POD

[![YouTube](http://i.ytimg.com/vi/xPwcyaeRcRk/hqdefault.jpg)](https://www.youtube.com/watch?v=xPwcyaeRcRk)

# Create provider (provider.yaml)

Using spacectl command

```
---
name: Example Provider
order: 1
provider: example
capability:
  general_service_account_schema:
  - example_schema_type0
  support_trusted_service_account: false
  supported_schema:
  - example_schema_type0
tags:
  color: '#FF9900'
  external_link_template: https://<%- data.account_id %>.example.com
  icon: https://raw.githubusercontent.com/cloudforet-io/artwork/main/logo/symbol/Cloudforet_symbol--dark-navy.png
template:
  service_account:
    schema:
      properties:
        account_id:
          minLength: 4.0
          title: Account ID
          type: string
      required:
      - account_id
      type: object
metadata:
  view:
    layouts:
      help:service_account:create:
        name: Creation Help
        options:
          markdown:
            en: "# Example Provider User Guide\n## Guide step 1\nHello Provider guide\n## guide Step 2\nHello Provider step 2"
        type: markdown
```

Execute API

```
spacectl exec create identity.Provider -f  provider.yaml
```

<img width="1076" alt="image" src="https://github.com/cloudforet-io/cloudforet/assets/3993088/5eb21a32-b58d-40fe-8db6-91b56dfb1f4e">

# Register local repository

To create schema, the repository service is needed. The default **managed-repo** is read only repository service. So you have to create **local** repository.

```
spacectl exec register repository.Repository -p name="My Private Repo" -p repository_type=local 
```

Execute API

```
root@spacectl-758c9d957c-45szb:~# spacectl exec register repository.Repository -p name="My Private Repo" -p repository_type=local
---
created_at: '2024-06-11T08:48:26.324Z'
name: My Private Repo
repository_id: repo-15e194c88cb7
repository_type: local
```

# Create Schema

file: schema.yaml

```
---
name: example_schema_type0
schema:
  order:
  - account_id
  - secret_field_1
  - secret_field_2
  properties:
    account_id:
      format: text
      minLength: 10
      title: Account ID
      type: string
    secret_field_1:
      format: password
      minLength: 8
      title: Secret Data 1
      type: string
    secret_field_2:
      format: password
      minLength: 8
      title: Secret Data 2
      type: string
  required:
  - account_id
  - secret_field_1
  type: object
service_type: secret.credentials
tags:
  description: Example Provider secret format
labels:
- example
```

Execute API

```
spacectl exec create repository.Schema -f schema.yaml
```

<img width="1023" alt="image" src="https://github.com/cloudforet-io/cloudforet/assets/3993088/adb7da2d-bd88-4e1b-be65-9cdb1765ecc5">

# Register Skeleton collector

> update ***YOUR_DOCKERHUB_REPO*** to your dockerhub organization name

for example

```
image: sunshout/plugin-example-inven-collector
```

file : plugin.yaml

```
---
name: Example Collector
service_type: inventory.Collector
image: YOUR_DOCKERHUB_REPO/plugin-example-inven-collector
capability: {}
tags:
  icon: https://raw.githubusercontent.com/cloudforet-io/artwork/main/logo/symbol/Cloudforet_symbol--dark-navy.png
template: {}
provider: example
```

Execute API

```
spacectl exec register repository.Plugin -f plugin.yaml
```
# Enable Skeleton collector
